Issues when upgrading IML manager (#676)
Fixes #673

When performing a ```yum update python2-iml-manager``` I saw the following:

```
Running transaction
  Updating   : python2-iml-manager-libs-4.0.6.0-5093.59.gb22519a.el7.noarch                                                                                                                                                               1/6
  Updating   : python2-iml-manager-cli-4.0.6.0-5093.59.gb22519a.el7.noarch                                                                                                                                                                2/6
  Updating   : python2-iml-manager-4.0.6.0-5093.59.gb22519a.el7.noarch                                                                                                                                                                    3/6
SELinux is enabled!
ValueError: Port tcp/8001 already defined
DB already accessible
Database tables already OK
Registering profile: /usr/share/chroma-manager/base_managed_RH7.profile
Registering profile: /usr/share/chroma-manager/base_monitored.profile
Registering profile: /usr/share/chroma-manager/default.profile
Registering profile: /usr/share/chroma-manager/posix_copytool_worker.profile
Registering profile: /usr/share/chroma-manager/robinhood_server.profile
Thank you for installing Chroma.  To complete your installation, please
run "chroma-config setup"
```

We shouldn't have a ```ValueError``` on the port and
we should print out an update message instead of an install message.

Signed-off-by: Joe Grund <jgrund@whamcloud.io>